common:
  port:
    http:
      name: http-port
      value: 8080
  name: data-query

hpa:
  behavior:
    - name: scaleDown
      type: Pods
      value: 1
      seconds:
        stabilization: 120
        period: 120
    - name: scaleUp
      type: Pods
      value: 1
      seconds:
        stabilization: 300
        period: 300
  replicas:
    min: 1
    max: 2
  resources:
    - name: memory
      value: 80
    - name: cpu
      value: 80

deployment:
  security:
    fs: 10001
    user: 10001
    group: 10001
  docker:
    image:
      name: data-query:latest
      pullPolicy: IfNotPresent
  update:
    max:
      surge: 1
      unavailable: 0
  limit:
    cpu: 700m
    memory: 1024Mi
    storage: 5000Mi
  probe:
    path: /health/status
    port: http-port
    values:
      - name: livenessProbe
        failureThreshold: 5
        seconds:
          period: 600
          initialDelay: 20
          timeout: 120
      - name: startupProbe
        failureThreshold: 12
        seconds:
          period: 20
          initialDelay: 20
          timeout: 120

service:
  type: ClusterIP

config:
  spring_profiles_active: dev
  http_port: 8080
